name: build and release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]  # 三个平台
#        os: [windows-latest, ubuntu-latest, macos-latest]  # 三个平台
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.4'

      - name: Install dependencies
        run: |
          ppi list
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list
#
#      - name: Build executable
#        run: |
#          pyinstaller your-script.py  # 打包脚本
#
#      - name: Update release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: |
#            dist/your-executable
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
